set nobackup
set nowrap
set ignorecase
set smartcase
set history=10000
set hlsearch
set incsearch
set backspace=indent,eol,start
set number
set showcmd
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set showtabline=2
set list listchars=tab:»·,trail:·
set termguicolors
set background=dark
setlocal shiftwidth=2

let NERDTreeShowHidden=1
let @/ = ""
let g:rspec_command = "Dispatch rspec {spec}"

" install plug if it is not already installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent execute "!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

" source .vimrc and :PlugInstall after changes
call plug#begin()
  Plug 'andreasvc/vim-256noir'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'mileszs/ack.vim'
  Plug 'preservim/NERDTree'
  Plug 'thoughtbot/vim-rspec'
  Plug 'tomtom/tcomment_vim'
  Plug 'tpope/vim-bundler'
  Plug 'tpope/vim-rails'
  Plug 'tpope/vim-dispatch'
call plug#end()

nmap <C-P> :FZF<CR>
nmap <leader>t :call RunCurrentSpecFile()<CR>
nmap <leader>s :call RunNearestSpec()<CR>
nmap <leader>l :call RunLastSpec()<CR>
nmap <leader>a :call RunAllSpecs()<CR>

noremap <leader>nt :NERDTreeToggle<CR>
noremap <c-up> <c-w>+
noremap <c-down> <c-w>-
noremap <c-left> <c-w>>
noremap <c-right> <c-w><

nnoremap Y y$
nnoremap <tab>   <c-w>w
nnoremap <S-tab> <c-w>W

colorscheme 256_noir
highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=233 guifg=NONE guibg=#121212
autocmd InsertEnter * highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=234 guifg=NONE guibg=#1c1c1c
autocmd InsertLeave * highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=233 guifg=NONE guibg=#121212
