set nobackup
set nowrap
set ignorecase
set smartcase
set history=10000
set hlsearch
set incsearch
set backspace=indent,eol,start
set number
set showcmd
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set showtabline=2
set laststatus=2
set list listchars=tab:»·,trail:·
set termguicolors
set background=dark
set exrc

setlocal shiftwidth=2

let NERDTreeShowHidden=1
let @/ = ""
let test#strategy = "dispatch"

augroup quickfix
    autocmd!
    autocmd FileType qf setlocal wrap
augroup END

" install plug if it is not already installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent execute "!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

" source .vimrc and :PlugInstall after changes
call plug#begin()
  Plug 'andreasvc/vim-256noir'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'mileszs/ack.vim'
  Plug 'preservim/NERDTree'
  Plug 'tomtom/tcomment_vim'
  Plug 'tpope/vim-bundler'
  Plug 'tpope/vim-rails'
  Plug 'tpope/vim-dispatch'
  Plug 'vim-test/vim-test'
call plug#end()

nmap <C-P> :FZF<CR>
nmap <leader>c :g#\({\n\)\@<=#.,/\.*[{}]\@=/-1 sort
nmap <leader>m `a

nmap <silent> <leader>u :TestNearest<CR>
nmap <silent> <leader>t :TestFile<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>a :TestSuite<CR>

noremap <leader>nt :NERDTreeToggle<CR>
noremap <c-up> <c-w>+
noremap <c-down> <c-w>-
noremap <c-left> <c-w>>
noremap <c-right> <c-w><

nnoremap Y y$
nnoremap <tab>   <c-w>w
nnoremap <S-tab> <c-w>W

colorscheme 256_noir
highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=233 guifg=NONE guibg=#121212
autocmd InsertEnter * highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=234 guifg=NONE guibg=#1c1c1c
autocmd InsertLeave * highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=233 guifg=NONE guibg=#121212
