# History, history, blame it on the history!

HISTSIZE=10000000
SAVEHIST=10000000

# Path
export PATH=/opt/homebrew/Cellar/imagemagic/7.1.0-52:$PATH

# RBEnv
eval "$(rbenv init - zsh)"

# Load
autoload -Uz compinit && compinit
autoload -Uz vcs_info
autoload -U colors && colors

# Prompt
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '(%b)'
setopt PROMPT_SUBST
PROMPT='%2~ %F{196}${vcs_info_msg_0_}%f # '

# Aliases
alias rel='source ~/.zshrc'
alias ls='ls -G'
alias be='bundle exec'
alias myip="/usr/local/bin/find_ip.rb"
alias his="history 1"

# Global aliases

# Functions
alias reach() { grep -IHrn $1 . }

# Additional local configuration
for conf in "$HOME/.config/zsh/config.d/"*.zsh; do
  source "${conf}"
done
unset conf

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform
